---
title: "Análise e Visualização de Dados da COVID-19"
subtitle: "Minicurso - DCX / CCAE / UFPB - 2020.4"
author: "Prof. Marcus Carvalho e Prof. Raquel Lopes"
output:
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
---

******

## Material do curso

Os vídeos e outros materiais de estudo estão postados no Google Classroom do minicurso.
As atividades práticas também deverão ser envias por lá.

******

### Semana 1

- [Slides 0: Apresentação do minicurso](slides/00-apresentacao.html)

- [Slides 1: Introdução à visualização de dados](slides/01-introducao-vis.html)

- [Lab 1: Instalando o R e criando o primeiro plot](labs/01-instalacao_r.html)

******

### Semana 2

- [Slides 2: Contexto da COVID-19](slides/02-contexto-covid.html)

- [Lab 2: Manipulação de dados e customização de gráficos](labs/02-manipulacao_customizacao.html)

******

### Semana 3

- [Lab 3: Manipulação e comparação de dados agrupados](labs/03-comparacao.html)

- [Lab 4: Seu relatório COVID-19](labs/04-seu_relatorio_covid19.html) [[Rmarkdown](https://github.com/analise-de-dados-ufpb/vis-covid/blob/master/labs/04-seu_relatorio_covid19.Rmd)]

******

### Semana 4

- [Slides 3: O que visualizar? Semântica e tipos de dados](slides/03-o-que-visualizar.html)

******

### Semana 5

- [Slides 4: Marcas e canais visuais](slides/04-marcas-canais.html)

******

### Semana 6

- [Slides 5: Análise exploratória de dados](slides/05-eda.html)
- [Lab 5: Sua análise exploratória de dados do e-SUS Notifica](labs/05-analise-exploratoria-esus.html) [[Rmarkdown](labs/05-analise-exploratoria-esus.Rmd), [Dados](data/dados-pb.csv.gz)]

******

### Semana 7

- [Lab 6: EDA, comparações e mapas](labs/06-eda-mapas.html) [[Rmarkdown](labs/06-eda-mapas.Rmd)]
